title: My blog
theme: minima # my theme
author: JustErbe
email: erbejustjoke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey. This is my personal blog. 
  In it, I will talk about my successes in programming and not only. 
  Here you can find out about my short life and my path to C programming.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
