title: My live blog
author: Semyon
email: erbejustjoke@gmail.com
description: > Hello! And this is my blog about my successes in programming and personal goals that are not related to code. I will try to make it interesting and informative.

theme: minima:
 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  JustErbe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
